# Generated by Django 2.1.5 on 2019-02-22 21:48
import re
from django.db import migrations
from apps.scrape.utils import get_page, get_data, get_race_code, get_race_name,\
        get_cand_code, get_cand_name


page = get_page()
data = get_data(page)


def init(apps,schema_editor):
    Race = apps.get_model('races', 'Race')
    Candidate = apps.get_model('candidates','Candidate')
    load_race_cboe_ids(Race)
    load_cand_cboe_ids(Race,Candidate)


def load_race_cboe_ids(Race):
    '''
    Manually add cboe_results_id for races
    '''
    race_names = set()
    for line in data:
        race_name = get_race_name(line)
        if race_name in race_names:
            continue # already added to db
        race_names.add(race_name)
        cboe_results_id = get_race_code(line)
        if race_name == 'Mayor':
            race = Race.objects.get(slug='city-mayor')
        elif race_name == 'Clerk':
            race = Race.objects.get(slug='city-clerk')
        elif race_name == 'Treasurer':
            race = Race.objects.get(slug='city-treasurer')
        elif 'Alderman' in race_name:
            ward_no = re.search(r'\d+', race_name).group()
            # ward nos correspond to chi.vote race ids
            race = Race.objects.get(id=int(ward_no))
        else:
            raise Exception
        if race:
            print(race_name,race.slug)
            race.cboe_results_id=cboe_results_id
            race.save()


def load_cand_cboe_ids(Race, Candidate):
    '''
    Add cboe_results_id for candidates based on race and last name
    '''
    from django.core.exceptions import ObjectDoesNotExist

    for datum in data:
        # get race object
        race_code = get_race_code(datum)

        try:
            race_obj = Race.objects.get(cboe_results_id=race_code)
        except ObjectDoesNotExist:
            # once the race codes stop matching, we're done
            break

        # get candidate data
        cand_code = get_cand_code(datum)
        cand_name = get_cand_name(datum)

        cand = lookup_our_cand(cand_name, race_obj, Candidate)
        if (cand):
            cand.cboe_results_id = cand_code
        else:
            import ipdb; ipdb.set_trace()
            pass
        cand.save()


def lookup_our_cand(cboe_name, race_obj, Candidate):
    from django.core.exceptions import ObjectDoesNotExist
    cand_obj = None

    try:
        cboe_first_name = cboe_name.split(' ')[0]
        cand_obj = race_obj.candidates.get(
            first_name__icontains=cboe_first_name)
    except ObjectDoesNotExist:
        try:
            cboe_last_name = cboe_name.split(' ')[-1]
            cand_obj = race_obj.candidates.get(
                last_name__icontains=cboe_last_name)
        except ObjectDoesNotExist:
            print(
                f'\nCould not identify {cboe_name} {race_obj}')
    
    # a special case    
    if not cand_obj and cboe_name == 'R. RODRIGUEZ SANCHEZ':
        cand_obj=Candidate.objects.get(last_name='Rodríguez-Sánchez')
   
    if cand_obj:
        print(cboe_name,cand_obj.full_name)
    return cand_obj




class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(init)
    ]
