# Generated by Django 2.1.5 on 2019-02-22 21:48
import re
from django.db import migrations


def load_race_cboe_ids(apps, schema_editor):
    '''
    Manually add cboe_results_id for races
    '''
    Race = apps.get_model('races', 'Race')

    Race.objects.filter(slug='city-mayor').update(cboe_results_id='0010')
    Race.objects.filter(slug='city-clerk').update(cboe_results_id='0011')
    Race.objects.filter(slug='city-treasurer').update(cboe_results_id='0012')

    for r in Race.objects.filter(slug__iendswith='alderman'):
        ward_no = re.search(r'\d+', r.slug).group()
        # e.g. 1st ward => 0013
        cboe_results_id = '00' + str(12 + int(ward_no))
        r.cboe_results_id = cboe_results_id
        r.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_race_cboe_ids,
                             reverse_code=migrations.RunPython.noop),
    ]
