# Generated by Django 2.1.5 on 2019-01-25 00:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0003_auto_20190124_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('elected', 'Elected'), ('candidate', 'Candidate'), ('inactive', 'Inactive')], default='candidate', max_length=25)),
                ('incumbent', models.BooleanField(default=False)),
                ('ballot_order', models.PositiveSmallIntegerField(default=0)),
                ('cboe_id', models.IntegerField()),
                ('isbe_id', models.IntegerField(blank=True, null=True)),
                ('br_id', models.IntegerField(blank=True, null=True)),
                ('ri_id', models.IntegerField(blank=True, null=True)),
                ('br_thumb_url', models.URLField(blank=True, null=True, verbose_name='Thumbnail URL')),
                ('br_photo_url', models.URLField(blank=True, null=True, verbose_name='Photo URL')),
                ('br_urls', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='URLs')),
                ('br_endorsements', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Endorsements')),
                ('br_experience', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Experience')),
                ('br_education', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Education')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Race')),
            ],
            options={
                'ordering': ['ballot_order'],
            },
        ),
        migrations.CreateModel(
            name='CandidateContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'email'), ('mobile', 'mobile'), ('campaign phone', 'campaign phone'), ('home address', 'home address'), ('campaign address', 'campaign address'), ('other', 'other')], default='email', max_length=25)),
                ('contact_value', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
    ]
