# Generated by Django 2.1.5 on 2019-01-21 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=25)),
                ('contact_value', models.CharField(max_length=50)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
        migrations.AddField(
            model_name='candidate',
            name='br_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cboe_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='isbe_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ri_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ballot_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidatecontact',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate'),
        ),
    ]
