# Generated by Django 2.1.5 on 2019-01-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_load_candidates_and_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecontact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
