# Generated by Django 2.1.5 on 2019-01-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20190127_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cboe_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
