# Generated by Django 2.1.5 on 2019-01-31 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_auto_20190127_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='races.Race'),
        ),
    ]
