# Generated by Django 2.1.5 on 2019-01-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_load_candidates_ballotready_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('elected', 'elected'), ('candidate', 'candidate'), ('inactive', 'inactive')], default='candidate', max_length=25),
        ),
        migrations.AlterField(
            model_name='candidatecontact',
            name='contact_type',
            field=models.CharField(choices=[('email', 'email'), ('mobile', 'mobile'), ('campaign phone', 'campaign phone'), ('home address', 'home address'), ('campaign address', 'campaign address'), ('other', 'other')], default='email', max_length=25),
        ),
    ]
