# Generated by Django 2.1.5 on 2019-01-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_auto_20190124_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('elected', 'Elected'), ('candidate', 'Candidate'), ('inactive', 'Inactive')], default='candidate', max_length=25),
        ),
    ]
