# Generated by Django 2.1.5 on 2019-01-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_load_candidates_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
    ]
