# Generated by Django 2.1.5 on 2019-01-18 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0002_load_offices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explainer', models.TextField()),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.Office')),
            ],
        ),
    ]
