# Generated by Django 2.1.5 on 2019-01-18 23:41
from django.db import migrations
from apps.races.models import Race
from apps.offices.models import Office

def load(apps,schema_editor):
    for office in Office.objects.all():
        race = Race.objects.create(
                office=office)
        race.save()


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(load)
    ]
