# Generated by Django 2.1.5 on 2019-01-25 20:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_load_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='explainer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
