# Generated by Django 2.1.5 on 2019-01-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_auto_20190125_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['office']},
        ),
    ]
