# Generated by Django 2.1.5 on 2019-02-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_auto_20190127_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='documenters_slug',
            field=models.CharField(blank=True, help_text='Embed will populate at https://embed.documenters.org/chivote-forums/[SLUG].html', max_length=20, null=True, verbose_name='Documenters.org embed slug'),
        ),
    ]
