# Generated by Django 2.1.5 on 2019-02-08 21:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_race_documenters_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='explainer_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='explainer_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
