# Generated by Django 2.1.7 on 2019-02-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0009_auto_20190208_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='cboe_id',
            field=models.TextField(blank=True, max_length=4, null=True),
        ),
    ]
