# Generated by Django 2.1.7 on 2019-03-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_race_cboe_results_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='are_cboe_results_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='cboe_results_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
