# Generated by Django 2.1.7 on 2019-03-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0011_auto_20190313_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='cboe_results_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
