# Generated by Django 2.1.5 on 2019-01-25 00:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_load_candidates_and_contacts'),
        ('races', '0003_auto_20190124_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hed', models.CharField(max_length=280)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('link', models.URLField()),
                ('source', models.CharField(max_length=200, verbose_name='Publisher')),
                ('candidate', models.ManyToManyField(blank=True, help_text='Double click, or select and click the arrow, to add or remove a candidate.', to='candidates.Candidate', verbose_name='Candidate(s)')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateStance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_short', models.CharField(max_length=280, verbose_name='Short stance')),
                ('statement_long', ckeditor.fields.RichTextField(verbose_name='Long stance')),
                ('date', models.DateField(blank=True, null=True)),
                ('link', models.URLField()),
                ('source', models.CharField(max_length=200, verbose_name='Publisher')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='candidatestance',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsfeed.Issue'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ManyToManyField(blank=True, help_text='Double click, or select and click the arrow, to add or remove an issue.', to='newsfeed.Issue', verbose_name='Issue(s)'),
        ),
        migrations.AddField(
            model_name='article',
            name='race',
            field=models.ManyToManyField(blank=True, help_text='Double click, or select and click the arrow, to add or remove a race.', to='races.Race', verbose_name='Race(s)'),
        ),
    ]
