# Generated by Django 2.1.5 on 2019-01-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hed', models.CharField(max_length=280)),
                ('link', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=200)),
                ('races', models.ManyToManyField(to='races.Race')),
            ],
        ),
    ]
