# Generated by Django 2.1.5 on 2019-01-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_load_candidates_ballotready_ids'),
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='candidate',
            field=models.ManyToManyField(blank=True, help_text='Double click, or select and click the arrow, to add or remove a candidate.', to='candidates.Candidate', verbose_name='Candidate(s)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ManyToManyField(blank=True, help_text='Double click, or select and click the arrow, to add or remove an issue.', to='newsfeed.Issue', verbose_name='Issue(s)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='race',
            field=models.ManyToManyField(blank=True, help_text='Double click, or select and click the arrow, to add or remove a race.', to='races.Race', verbose_name='Race(s)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(max_length=200, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='candidatestatement',
            name='issue',
            field=models.ManyToManyField(blank=True, help_text='Double click, or select and click the arrow, to add or remove an issue.', to='newsfeed.Issue', verbose_name='Issue(s)'),
        ),
        migrations.AlterField(
            model_name='candidatestatement',
            name='source',
            field=models.CharField(max_length=200, verbose_name='Publisher'),
        ),
    ]
