# Generated by Django 2.1.5 on 2019-01-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hed',
            field=models.CharField(max_length=280, unique=True, verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
