# Generated by Django 2.1.5 on 2019-01-22 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_load_candidates_and_contacts'),
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('issue', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
    ]
