# Generated by Django 2.1.5 on 2019-01-29 10:29

from django.db import migrations, models


def reorder(apps, schema_editor):
    Issue = apps.get_model('newsfeed', 'Issue')
    order = 0
    for item in Issue.objects.all():
        order += 1
        item.issue_order = order
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_auto_20190124_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['issue_order']},
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(reorder),
    ]
