# Generated by Django 2.1.5 on 2019-01-24 16:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_load_candidates_ballotready_ids'),
        ('newsfeed', '0002_auto_20190124_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_short', models.CharField(max_length=280)),
                ('statement_long', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField()),
                ('link', models.URLField()),
                ('source', models.CharField(max_length=200, verbose_name='Publisher')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidatestatement',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidatestatement',
            name='issue',
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='CandidateStatement',
        ),
        migrations.AddField(
            model_name='candidatestance',
            name='issue',
            field=models.ManyToManyField(blank=True, help_text='Double click, or select and click the arrow, to add or remove an issue.', to='newsfeed.Issue', verbose_name='Issue(s)'),
        ),
    ]
