# Generated by Django 2.1.5 on 2019-01-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_auto_20190124_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestance',
            name='date',
            field=models.DateField(),
        ),
    ]
