# Generated by Django 2.1.5 on 2019-01-31 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_auto_20190129_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='candidate',
            new_name='candidates',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='issue',
            new_name='issues',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='race',
            new_name='races',
        ),
    ]
