# Generated by Django 2.1.5 on 2019-01-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0004_auto_20190131_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='candidates',
            field=models.ManyToManyField(blank=True, help_text='Double click, or select and click the arrow, to add or remove a candidate.', related_name='articles', to='candidates.Candidate', verbose_name='Candidate(s)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='issues',
            field=models.ManyToManyField(blank=True, help_text='Double click, or select and click the arrow, to add or remove an issue.', related_name='articles', to='newsfeed.Issue', verbose_name='Issue(s)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='races',
            field=models.ManyToManyField(blank=True, help_text='Double click, or select and click the arrow, to add or remove a race.', related_name='articles', to='races.Race', verbose_name='Race(s)'),
        ),
    ]
