# Generated by Django 2.1.5 on 2019-01-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0004_auto_20190124_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatestance',
            name='issue',
        ),
        migrations.AddField(
            model_name='candidatestance',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsfeed.Issue'),
        ),
    ]
