# Generated by Django 2.1.5 on 2019-01-31 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0005_auto_20190131_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatestance',
            old_name='statement_long',
            new_name='stance_long',
        ),
        migrations.RenameField(
            model_name='candidatestance',
            old_name='statement_short',
            new_name='stance_short',
        ),
    ]
