# Generated by Django 2.1.5 on 2019-01-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0005_auto_20190124_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
