# Generated by Django 2.1.5 on 2019-01-31 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0006_auto_20190131_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestance',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stances', to='candidates.Candidate'),
        ),
        migrations.AlterField(
            model_name='candidatestance',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stances', to='newsfeed.Issue'),
        ),
    ]
