# Generated by Django 2.1.5 on 2019-01-24 16:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0006_auto_20190124_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
