# Generated by Django 2.1.5 on 2019-01-24 20:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0007_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestance',
            name='statement_long',
            field=ckeditor.fields.RichTextField(verbose_name='Long stance'),
        ),
        migrations.AlterField(
            model_name='candidatestance',
            name='statement_short',
            field=models.CharField(max_length=280, verbose_name='Short stance'),
        ),
    ]
