# Generated by Django 2.1.5 on 2019-01-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0008_auto_20190124_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hed',
            field=models.CharField(max_length=280, unique=True, verbose_name='Headline'),
        ),
    ]
