# Generated by Django 2.1.5 on 2019-02-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0008_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestance',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
