# Generated by Django 2.1.5 on 2019-02-12 22:58

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Article = apps.get_model('newsfeed', 'Article')
    TaggedArticle = apps.get_model('newsfeed', 'TaggedArticle')
    for article in Article.objects.all():
        for race in article.races.all():
            TaggedArticle(
                article=article,
                race=race,
                is_pinned=False
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0010_taggedarticle'),
    ]

    operations = [
        migrations.RunPython(create_through_relations,
                             reverse_code=migrations.RunPython.noop),
    ]
