# Generated by Django 2.1.5 on 2019-02-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0009_auto_20190208_1530'),
        ('newsfeed', '0012_remove_article_races'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='races',
            field=models.ManyToManyField(blank=True, help_text='Double click, or select and click the arrow, to add or remove a race.', related_name='articles', through='newsfeed.TaggedArticle', to='races.Race', verbose_name='Race(s)'),
        ),
    ]
