# Generated by Django 2.1.5 on 2019-02-13 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0013_article_races'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggedarticle',
            options={'ordering': ('is_pinned', '-article__date')},
        ),
        migrations.AlterField(
            model_name='taggedarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_articles', to='newsfeed.Article'),
        ),
        migrations.AlterField(
            model_name='taggedarticle',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Pin?'),
        ),
        migrations.AlterField(
            model_name='taggedarticle',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_races', to='races.Race'),
        ),
    ]
