# Generated by Django 2.1.5 on 2019-02-13 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0014_auto_20190212_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggedarticle',
            options={'ordering': ('-is_pinned', '-article__date')},
        ),
        migrations.AlterField(
            model_name='taggedarticle',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_articles', to='races.Race'),
        ),
    ]
