# Generated by Django 2.1.5 on 2019-01-18 21:26

from django.db import migrations
from apps.places.models import Place
from apps.offices.models import Office

def load(apps,schema_editor):
    city = Place.objects.get(citywide=True)

    # alderppl
    for ward in Place.objects.filter(ward_no__isnull=False):
        office = Office.objects.create(
                name = ward.name + ' Alderman',
                place=ward
                )
        office.save()

    # city offices
    for office_name in ('Mayor','Clerk','Treasurer'):
        office = Office.objects.create(
                name=office_name,
                place=city
                )
        office.save()



class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(load)
    ]
