# Generated by Django 2.1.5 on 2019-02-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_auto_20190127_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='name_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='name_es',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
