# Generated by Django 2.1.5 on 2019-01-22 18:05

from django.db import migrations
from apps.site_content.models import ContentItem 

def load(apps,schema_editor):
    for item in ['faq','about','quiz']:
        ci = ContentItem.objects.create(
                slug = item
                )
        ci.save()


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(load)
    ]
