# Generated by Django 2.1.5 on 2019-01-24 16:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_load_content_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
