# Generated by Django 2.1.5 on 2019-01-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0004_contentitem_helmet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='helmet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
