# Generated by Django 2.1.5 on 2019-01-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0007_contentitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
