# Generated by Django 2.1.5 on 2019-02-08 21:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0008_contentitem_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='content_es',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='description_en',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='description_es',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='slug_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='slug_es',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
