# Generated by Django 2.1.5 on 2019-01-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('citywide', models.BooleanField()),
                ('ward_no', models.IntegerField(null=True)),
            ],
        ),
    ]
