# Generated by Django 2.1.5 on 2019-01-18 18:53

from django.db import migrations
from apps.places.models import Place


def load(apps,schema_editor):
    for ward_no in range(1,51):
        ward=Place.objects.create(
            name='Ward ' + str(ward_no),
            citywide=False,
            ward_no=ward_no)
        ward.save()
    city=Place.objects.create(
            name='City of Chicago',
            citywide=True)
    city.save()

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(load)
    ]
