# Generated by Django 2.1.5 on 2019-01-19 19:19

from django.db import migrations
from apps.questionnaires.models import Question

questions = {
        'imp_issue': 'What do you think is the most important issue facing your ward and how would you address it?',
        'rent_ctrl': 'If the state lifted the ban on rent control, would you support rent control in Chicago?',
        'ald_pre': 'Do you support aldermanic prerogative?',
        'school_bd': 'Do you support an elected school board, "hybrid" school board, or mayoral control?',
        'pension': 'How should Chicago pay for its required pension contributions?',
        'cpd_acct': 'Which proposal for civilian oversight of the police department do you support?',
        'term_limit': 'Are you in favor of a two-term limit for the mayor and aldermen?',
        'fair_maps': 'Are you in favor of an independent commission to draw the city\'s next ward map?',
        'cba': 'Do you support a community benefits agreement for the Obama Presidential Center and similar large developments?',
        'tif': 'Would you change how the city uses TIFs? If so, how?',
        }



def load(apps,schema_editor):
    for question in questions:
        q = Question.objects.create(
                question_slug=question,
                question_text=questions[question],
                )
        q.save()

class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(load)
    ]
