# Generated by Django 2.0 on 2018-10-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181030_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter the natural language (e.g. English, French, Japanese, etc.)', max_length=200),
        ),
    ]
