# Generated by Django 2.0 on 2018-10-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20181030_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Format: MM/DD/YYYY', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Format: MM/DD/YYYY', null=True, verbose_name='Died'),
        ),
    ]
